package:
  name: cohere
  version: "1.4"

source:
  path: .

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python=3.7.6
    - cython
    - numpy

  run:
    - numpy
    - python=3.7.6
    - tifffile
    - pylibconfig2
    - xrayutilities
    - pyparsing
    - mayavi
    - psutil


about:
  home: https://github.com/advancedPhotonSource/cdi
  license: BSD
  license_file: LICENSE
  summary: Implement and parallelize genetic algorithms and phase retrieval methods for Bragg CDI techniques.
