package:
  name: cohere
  version: "2.3"

source:
  path: .

build:
  number: 0

requirements:
  host:
    - python=3.8
    - numpy

  run:
    - python=3.8
    - numpy
    - gputil
    - tensorflow
    - scikit-learn
    - tifffile
    - psutil

about:
  home: https://github.com/advancedPhotonSource/cohere
  license: BSD
  license_file: LICENSE
  summary: AI, parallelized genetic algorithms and phase retrieval methods for Bragg CDI techniques.
