# #########################################################################
# Copyright (c) , UChicago Argonne, LLC. All rights reserved.             #
#                                                                         #
# See LICENSE file.                                                       #
# #########################################################################

"""
Error dictionaries and lookup map name dictionary
"""
__author__ = "David Cyl"
__copyright__ = "Copyright (c) 2016, UChicago Argonne, LLC."
__docformat__ = 'restructuredtext en'

config_error = {'File':['File does not exist','Cannot Read File',
                        'Parsing error, check parenthesis,quotation syntax'],
                'Workingdir':['Working_dir parameter should be a string',
                              'Working_dir parameter parsing error'],
                'ExperimentID':['experiment_id parameter should be string',
                                'experiment_id parameter parsing error'],
                'Scan':['scan parameter should be a string',
                        'scan parameter parsing error'],
                'Specfile':['specfile parameter should be string',
                            'specfile parameter parsing error']}
config_prep_error = {'File':['No configuration file',
                             'cannot read configuration file',
                             'Parsing error, check parenthesis,quotation syntax'],
                     'Roi':['roi parameter should be a list of int'],
                     'Datadir':['data_dir parameter should be string',
                                'data_dir parameter parsing error'],
                     'Darkfield':['darkfield_filename parameter should be string',
                                  'darkfield_filename parameter parsing error'],
                     'Whitefield':['whitefield_filename parameter should be string',
                                   'whitefield_filename parameter parsing error'],
                     'Excludescans':['exclude scans should be a list'],
                     'MinFiles':['min_files should be int',
                                 'min_files parameter parsing error'],
                     'Separatescans':['separate_scans parameter should be true or false',
                                      'separate_scans parameter parsing error']}
config_disp_error = {'File':['No configuration file',
                             'Cannot read configuration file',
                             'Parsing error, check parenthesis,quotation syntax'],
                     'Diffractometer':['diffractometer parameter should be string',
                                       'diffractometer parameter parsing error'],
                     'Crop':['crop should be list',
                             'crop should be a list of int or float',
                             'crop parameter parsing error'],
                     'Energy':['energy should be float',
                               'energy parameter parsing error'],
                     'Delta':['delta should be float',
                              'delta parameter parsing error'],
                     'Gamma':['gamma should be float',
                              'gamma parameter parsing error'],
                     'Detdist':['detdist should be float',
                                'detdist parameter parsing error'],
                     'Dth':['dth should be float',
                            'dth parameter parsing error'],
                     'Pixel':['pixel should be a list',
                              'pixel values should be float',
                              'pixel parameter parsing error']}
config_data_error = {'File':['No configuration file',
                             'Cannot read configuration file',
                             'Parsing error, check parenthesis,quotation syntax'],
                     'Datadir':['data_dir parameter should be string',
                                'data_dir parameter parsing error'],
                     'Adjustdimensions':['adjust_dimensions should be a list'],
                     'Centershift':['center_shift should be a list'],
                     'Binning':['binning should be a list'],
                     'Intensitythreshold':['intensity_threshold should be float',
                                           'intensity_threshold parameter parsing error'],
                     'Aliens':['aliens should be a list of alien blocks (lists)',
                               'aliens is not a list of ints',
                               'misconfigured alien, each alien is defined by list of six int',
                               'aliens parameter parsing error'],
                     'AlienFile':['alien_file should be a string (mask file name)'],
                     'Aa1sizethreshold':['AA1_size_threshold should be float',
                                         'AA1_size_threshold parameter parsing error'],
                     'Aa1asymthreshold':['AA1_asym_threshold should be float',
                                         'AA1_asym_threshold parameter parsing error'],
                     'Aa1minpts':['AA1_min_pts should be int',
                                  'AA1_min_pts parameter parsing error'],
                     'Aa1eps':['AA1_eps should be float',
                               'AA1_eps parameter parsing error'],
                     'Aa1ampthreshold':['AA1_amp_threshold should be float',
                                        'AA1_amp_threshold parameter parsing error'],
                     'Aa1savearrs':['AA1_save_arrs parameter should be true or false',
                                    'AA1_save_arrs parameter parsing error'],
                     'Aa1expandcleanedsigma':['AA1_expandcleanedsigma should be float',
                                              'AA1_expandcleanedsigma parameter parsing error']}
config_rec_error = {'File':['No configuration file',
                             'Cannot read configuration file',
                             'Parsing error, check parenthesis,quotation syntax'],
                    'Datadir':['data_dir parameter should be string',
                               'data_dir parameter parsing error'],
                    'Savedir':['save_dir parameter should be string',
                               'save_dir parameter parsing error'],
                    'Cont':['cont parameter should be true or false',
                            'cont parameter parsing error'],
                    'Continuedir':['continue_dir parameter should be string',
                                   'continue_dir parameter parsing error'],
                    'Reconstruction':['reconstructions parameter should be int',
                                      'reconstructions parameter parsing error'],
                    'Device':['device not a list on ints',
                              'device parameter parsing error'],
                    'Algorithmsequence':['algorithm_sequence should be a list',
                                         'algorithm_sequence configuration error, the repeat factor should be int',
                                         'algorithm_sequence configuration error, the sequence element should be a list',
                                         'algorithm_sequence configuration error, algorithm should be str',
                                         'algorithm_sequence configuration error, algorithm should be "ER" or "HIO"',
                                         'algorithm_sequence configuration error, algorithm repeat should be int',
                                         'missing mandatory algorithm_sequence parameter',
                                         'algorithm_sequence parameter parsing error'],
                    'Hiobeta':['hiobeta parameter should be float',
                            'hiobeta parameter parsing error'],
                    'Generations':['ga_generations parameter should be int',
                                   'generations parameter parsing error'],
                    'Gametrics':['ga_metrics is not a list',
                                 'non supported metric option used '
                                 'ga_metrics list can include only following strings:'
                                 ' "chi", "sharpness", "summed_phase", "area"',
                                 'ga_metrics parameter parsing error'],
                    'Gabreedmodes':['ga_breed_mode is not a list',
                                    'non supported breed mode used '
                                    'ga_breed_modes list can include only following strings:'
                                    ' “none”, “sqrt_ab”, “dsqrt”,“pixel_switch”, “b_pa”, “2ab_a_b”, “2a_b_pa”,'
                                    ' “sqrt_ab_pa”, “sqrt_ab_pa_recip”, “sqrt_ab_recip”,“max_ab”, “max_ab_pa”, '
                                    '“min_ab_pa”, “avg_ab”, “avg_ab_pa"',
                                    'ga_breed_modes parameter parsing error'],
                    'Gacullings':['List_int error',
                                  'ga_cullings parameter parsing error'],
                    'Gashrinkwrapthresholds':['List Float Error',
                                              'ga_shrink_wrap_thresholds parameter parsing error'],
                    'Gashrinkwrapgausssigmas':['List Float Error',
                                               'ga_shrink_wrap_gauss_sigmas parameter parsing error'],
                    'Galowpassfiltersigmas':['List Float Error',
                                             'ga_shrink_wrap_gauss_sigmas parameter parsing error'],
                    'Gagenpcstart':['ga_gen_pc_start parameter should be int',
                                    'ga_gen_pc_start parameter parsing error'],
                    'Twintrigger':['List Int Error'],
                    'Twinhalves':['List Int Error',
                                  'twin_halves parameter parsing error'],
                    'Shrinkwraptrigger':['List Int Error'],
                    'Shrinkwraptype':['shrink_wrap_type parameter should be string',
                                      'supporting shrink_wrap_type "GAUSS"',
                                      'shrink_wrap_type parameter parsing error'],
                    'Shrinkwrapthreshold':['shrink_wrap_threshold should be float',
                                           'shrink_wrap_threshold parameter parsing error'],
                    'Shrinkwrapgausssigma':['shrink_wrap_gauss_sigma should be float',
                                            'shrink_wrap_gauss_sigma parameter parsing error'],
                    'Initialsupportarea':['initial_support_area should be list',
                                          'initial_support_area should be a list of int or float',
                                          'initial_support_area parameter parsing error'],
                    'Phasesupporttrigger':['List Int Error'],
                    'Phmphasemin':['phm_phase_min should be float',
                                   'phm_phase_min parameter parsing error'],
                    'Phmphasemax':['phm_phase_max should be float',
                                   'phm_phase_max parameter parsing error'],
                    'Pcinterval':['List Int Error'],
                    'Pctype':['pc_type parameter should be string',
                              'pc_type parameter can be configured "LUCY"',
                              'pc_type parameter parsing error'],
                    'Pclucyiterations':['pc_LUCY_iterations should be int',
                                       'pc_LUCY_iterations parameter parsing error'],
                    'Pcnormalize':['pc_normalize parameter should be true or false',
                                   'pc_normalize parameter parsing error'],
                    'Pclucykernel':['List Int Error',
                                    'pc_LUCY_kernel parameter must be configured when partial coherence feature in active',
                                    'pc_LUCY_kernel parameter parsing error'],
                    'Resolutiontrigger':['List Int Error'],
                    'Lowpassfilterswsigmarange':['List Float Error',
                                                 'lowpass_filter_sw_sigma_range parameter parsing error'],
                    'Lowpassfilterrange':['List Float Error',
                                          'lowpass_filter_range parameter parsing error'],
                    'Averagetrigger':['List Int Error'],
                    'Progresstrigger':['List Int Error']}

config_map_names = {'config_error_map_file':config_error,
                    'config_prep_error_map_file':config_prep_error,
                    'config_disp_error_map_file':config_disp_error,
                    'config_data_error_map_file':config_data_error,
                    'config_rec_error_map_file':config_rec_error}
